In [150]:
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.neighbors import 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import random
import numpy as np
obj_iris= load_iris()
data=obj_iris.data
target=obj_iris.target
train_data,test_data,train_target,test_target=train_test_split(obj_iris.data,obj_iris.target,test_size=0.2)
""""train_data_array=np.array(train_data)
test_data_array=np.array(test_data)
train_target_array=np.array(train_target)
test_target_array=np.array(test_target)"""
knn_train_data=train_data[:,:3]
knn_test_data=test_data[:,:3]
dtc_train_data=train_data[:,1:]
dtc_test_data=test_data[:,1:]
rf_train_data=train_data[:,[0,1,3]]
rf_test_data=test_data[:,[0,1,3]]
gbc_train_data=train_data[:,[0,2,3]]
gbc_test_data=test_data[:,[0,2,3]]
print(dtc_train_data.shape)
#print(knn_train_data.shape)
#print(data)
#print(target)
#print(train_data)
#print(train_data)
#print(nn_train_data)
#print(nn_test_data)

(120, 3)


In [156]:
obj_knn=KNeighborsClassifier()
obj_knn.fit(knn_train_data,train_target) 
knn_prediction=obj_knn.predict(knn_test_data) 
print(knn_prediction) 
knn_accuracy=accuracy_score(test_target,knn_prediction)
print("Accuracy=",knn_accuracy)

[2 2 0 0 2 0 2 2 0 1 0 1 2 2 0 0 0 0 1 2 2 1 2 2 1 0 0 0 1 1]
Accuracy= 0.9333333333333333


In [158]:

from sklearn.tree import DecisionTreeClassifier
obj_dtc=DecisionTreeClassifier()
obj_dtc.fit(dtc_train_data,train_target)
dtc_prediction=obj_dtc.predict(dtc_test_data)
print(dtc_prediction)
dtc_accuracy=accuracy_score(test_target,dtc_prediction)
print("Accuracy=",dtc_accuracy)

[2 2 0 0 1 0 2 2 0 1 0 1 2 2 0 0 0 0 1 2 2 1 2 2 2 0 0 0 1 1]
Accuracy= 1.0


In [112]:
from sklearn.ensemble import RandomForestClassifier
obj_rf=RandomForestClassifier()
obj_rf.fit(rf_train_data,train_target)
rf_prediction=obj_rf.predict(rf_test_data)
print(rf_prediction)
rf_accuracy=accuracy_score(test_target,rf_prediction)
print("Accuracy=",rf_accuracy)

[2 2 2 2 1 1 0 2 1 2 0 1 1 0 1 2 1 0 2 1 2 2 0 0 0 1 0 1 0 2]
Accuracy= 1.0


In [157]:
from sklearn.ensemble import GradientBoostingClassifier
obj_gbc=GradientBoostingClassifier()
obj_gbc.fit(gbc_train_data,train_target)
gbc_prediction=obj_gbc.predict(gbc_test_data)
print(gbc_prediction)
gbc_accuracy=accuracy_score(test_target,gbc_prediction)
print("Accuracy=",gbc_accuracy)

[2 2 0 0 1 0 2 2 0 1 0 1 2 2 0 0 0 0 1 2 2 1 2 2 1 0 0 0 1 1]
Accuracy= 0.9666666666666667


In [162]:
prediction_final=[]
for i in range(0,len(test_target)):
    l=[]
    count_0=count_1=count_2=0
    l.append(knn_prediction[i])
    l.append(dtc_prediction[i])
    l.append(rf_prediction[i])
    l.append(gbc_prediction[i])
    for j in l:
            if(j==0):
                count_0=count_0+1
            elif(j==1):
                count_1=count_1+1
            elif(j==2):
                count_2=count_2+1
    if(count_0>count_1 and count_0>count_2):
        prediction_final.append(0)
    elif(count_1>count_0 and count_1>count_2):
        prediction_final.append(1)
    elif(count_2>count_0 and count_2>count_1):
        prediction_final.append(2)
    elif(count_0==count_1 and (count_0>count_2 or count_1>count_2)):
        prediction_final.append(random.choice([0,1]))
    elif(count_0==count_2 and (count_0>count_1 or count_2>count_1)):
        prediction_final.append(random.choice([0,2]))
    elif(count_2==count_1 and (count_1>count_0 or count_2>count_0)):
        prediction_final.append(random.choice([2,1])) 
                                

final_accuracy=accuracy_score(test_target,prediction_final)
print("Final Accuracy=",final_accuracy)

Final Accuracy= 0.9666666666666667
